import { KeynoteSpeaker, Speaker } from './types';

export const KEYNOTE_SPEAKER: KeynoteSpeaker = {
  title: 'AX: Transforming into an AI-Native Company',
  organization: 'LG AI연구원',
  name: '이홍락',
  role: 'CSAI',
};

export const SPEAKERS: Speaker[] = [
  // ── Track A · 거시환경 ──────────────────────────────────────────────────────
  {
    id: 'A-1',
    trackId: 'A',
    sessionNumber: 1,
    title: '2027 사업계획의 첫 번째 전제: 성장·물가·교역의 새 질서',
    organization: '대외경제정책연구원',
    name: '윤상하 실장',
    isTbd: false,
  },
  {
    id: 'A-2',
    trackId: 'A',
    sessionNumber: 2,
    title: '모두가 타깃이 되는 세계: 2027 지정학 리스크와 한국 기업의 선택',
    organization: '중앙대학교',
    name: '이승주 교수',
    isTbd: false,
  },
  {
    id: 'A-3',
    trackId: 'A',
    sessionNumber: 3,
    title: '에너지·물류 초크포인트: 원가와 공급망을 흔드는 다음 충격',
    organization: '삼일PwC',
    name: '강명수 국제통상솔루션센터장',
    isTbd: false,
  },
  {
    id: 'A-4',
    trackId: 'A',
    sessionNumber: 4,
    title: '환율·금리·자본비용: 2027 재무 전략의 리스크 지도',
    isTbd: true,
  },
  {
    id: 'A-5',
    trackId: 'A',
    sessionNumber: 5,
    title: 'K자형 양극화의 한국 경제: 2027 성장 기회와 방어 전략',
    organization: '현대경제연구원',
    name: '주원 실장',
    isTbd: false,
  },
  {
    id: 'A-6',
    trackId: 'A',
    sessionNumber: 6,
    title: '불확실성을 숫자로 바꾸는 시나리오 경영: 예산과 실행계획의 기술',
    isTbd: true,
  },

  // ── Track B · 경영전략·혁신 ──────────────────────────────────────────────────
  {
    id: 'B-1',
    trackId: 'B',
    sessionNumber: 1,
    title: '연간 계획의 종말: AI Adaptive Planning으로 전략을 다시 짜다',
    isTbd: true,
  },
  {
    id: 'B-2',
    trackId: 'B',
    sessionNumber: 2,
    title: 'AI Native 도약의 첫 조건: 성장을 막는 레거시를 버리는 법',
    isTbd: true,
  },
  {
    id: 'B-3',
    trackId: 'B',
    sessionNumber: 3,
    title: 'Dual AX 전략: 사업 모델과 실행 역량을 동시에 바꾸다',
    isTbd: true,
  },
  {
    id: 'B-4',
    trackId: 'B',
    sessionNumber: 4,
    title: '[AX사례] 제품을 넘어 생태계로: 플랫폼 기업은 어떻게 비즈니스를 재정의했나',
    isTbd: true,
  },
  {
    id: 'B-5',
    trackId: 'B',
    sessionNumber: 5,
    title: '[AX사례] 실행 속도의 혁명: 하이퍼 스냅스 조직은 어떻게 움직이는가',
    isTbd: true,
  },
  {
    id: 'B-6',
    trackId: 'B',
    sessionNumber: 6,
    title: '실리콘밸리의 극단적 AX: \'1인 유니콘\'이 던지는 성장의 질문',
    isTbd: true,
  },

  // ── Track C · AX · Tech ──────────────────────────────────────────────────────
  {
    id: 'C-1',
    trackId: 'C',
    sessionNumber: 1,
    title: '스틸칼라의 등장: 피지컬 AI가 산업 현장을 바꾸는 방식',
    isTbd: true,
  },
  {
    id: 'C-2',
    trackId: 'C',
    sessionNumber: 2,
    title: '테크 드래곤의 비상: 중국 AI 굴기가 바꾸는 경쟁의 판',
    organization: '한양대학교',
    name: '백서인 교수',
    isTbd: false,
  },
  {
    id: 'C-3',
    trackId: 'C',
    sessionNumber: 3,
    title: 'AI 투자의 성패: 거품과 워크슬롭을 넘어 ROI를 만드는 법',
    isTbd: true,
  },
  {
    id: 'C-4',
    trackId: 'C',
    sessionNumber: 4,
    title: '[AX사례] 전사 AI 도입의 현실: 성공 조건과 실패 패턴',
    organization: 'KPMG',
    name: '이동근 AI센터장',
    isTbd: false,
  },
  {
    id: 'C-5',
    trackId: 'C',
    sessionNumber: 5,
    title: '자율 경제 에이전트(AEA): AI가 결정하는 시대의 통제와 책임',
    isTbd: true,
  },
  {
    id: 'C-6',
    trackId: 'C',
    sessionNumber: 6,
    title: '통제인가 자율인가: 새도우 AI를 성과로 바꾸는 조직 설계',
    isTbd: true,
  },

  // ── Track D · 마케팅 ────────────────────────────────────────────────────────
  {
    id: 'D-1',
    trackId: 'D',
    sessionNumber: 1,
    title: 'AI 네이티브 소비자의 탄생: 2027 고객은 어떻게 선택하는가',
    organization: '트렌드코리아컴퍼니',
    name: '전미영 박사',
    isTbd: false,
  },
  {
    id: 'D-2',
    trackId: 'D',
    sessionNumber: 2,
    title: '검색 이후의 브랜드 전략: AI가 바꾼 구매 여정의 새 규칙',
    organization: 'Kearney',
    name: '윤성훈 파트너',
    isTbd: false,
  },
  {
    id: 'D-3',
    trackId: 'D',
    sessionNumber: 3,
    title: 'AI 시대의 미디어 투자 전략: 채널 믹스와 성과 극대화의 새 공식',
    organization: '한국종합예술원',
    name: '이승무 교수',
    isTbd: false,
  },
  {
    id: 'D-4',
    trackId: 'D',
    sessionNumber: 4,
    title: '[AX사례] 퍼포먼스 마케팅의 재설계: AI 측정·최적화와 인간의 판단',
    organization: '고려대학교',
    name: '송수진 교수',
    isTbd: false,
  },
  {
    id: 'D-5',
    trackId: 'D',
    sessionNumber: 5,
    title: 'AI 네이티브 마케팅 조직: 사람과 에이전트는 어떻게 협업하는가',
    isTbd: true,
  },
  {
    id: 'D-6',
    trackId: 'D',
    sessionNumber: 6,
    title: '[AX사례] 고객 경험의 AX: AI는 접점을 어떻게 바꾸는가',
    isTbd: true,
  },

  // ── Track E · 조직·리더십 ───────────────────────────────────────────────────
  {
    id: 'E-1',
    trackId: 'E',
    sessionNumber: 1,
    title: '글로벌 빅테크가 다시 짠 일의 구조: AI Native 직무 재설계',
    organization: '동국대학교',
    name: '이중학 교수',
    isTbd: false,
  },
  {
    id: 'E-2',
    trackId: 'E',
    sessionNumber: 2,
    title: '프롬프트가 업무 능력이 된 시대: 임직원 AI 리스킬링 전략',
    isTbd: true,
  },
  {
    id: 'E-3',
    trackId: 'E',
    sessionNumber: 3,
    title: '프롬프트 리더십: 구성원의 AI 잠재력을 깨우는 리더의 역할',
    isTbd: true,
  },
  {
    id: 'E-4',
    trackId: 'E',
    sessionNumber: 4,
    title: '[AX사례] AI Native HR: 채용부터 평가까지 인재 의사결정을 바꾸다',
    organization: 'SAP',
    name: '한광모 본부장',
    isTbd: false,
  },
  {
    id: 'E-5',
    trackId: 'E',
    sessionNumber: 5,
    title: '[AX사례] 전사 AI 내재화의 조건: 임원진은 어떻게 변화를 밀어붙였나',
    isTbd: true,
  },
  {
    id: 'E-6',
    trackId: 'E',
    sessionNumber: 6,
    title: '[AX사례] 연공서열과 AI 속도의 충돌: 한국형 조직의 현실적 전환법',
    isTbd: true,
  },
];
